### PR TITLE
[invite] Add eslint and Prettier to invite-bot app

### PR DESCRIPTION
**Pull request by rcebulko**

### CODE REVIEW

**Comment by danielrozenberg** [comment]
Isn't Prettier in the base directory of this repo? 🤔

**Comment by rcebulko** [comment]
> Isn't Prettier in the base directory of this repo?

Different configs and plugins are needed for typescript

**Comment by danielrozenberg** [comment]
> > Isn't Prettier in the base directory of this repo?
> 
> Different configs and plugins are needed for typescript

Ah, good to know. Maybe we can still somehow have one base config for it (or I can force myself to convert all my JS apps to TS 🙃)

**Comment by rsimha** [comment]
Delayed LGTM :)

**Pull request merged**
