### PR TITLE
[invite] Add build target for invite bot files

### PR DESCRIPTION
**Pull request by rcebulko**
Right now, every time I submit a PR for invite-bot, all build targets get run by default. This defines a new build target for PRs touching files under `invite/`

Addresses #687

### CODE REVIEW

**Comment by estherkim** [comment]
I'd go one step further and start running invite unit tests in our CI.

**Comment by rcebulko** [comment]
> I'd go one step further and start running invite unit tests in our CI.

Nice catch! I forgot that the actual tests to run lived somewhere else

**Comment by estherkim** [comment]
A `UnhandledPromiseRejectionWarning` here: https://travis-ci.org/ampproject/amp-github-apps/builds/649548856#L253-L254

I'm ok with skipping tests since we just want to hook them up to Travis, but we should get a clean run :+1:

**Comment by rcebulko** [comment]
> A `UnhandledPromiseRejectionWarning` here: https://travis-ci.org/ampproject/amp-github-apps/builds/649548856#L253-L254
> 
> I'm ok with skipping tests since we just want to hook them up to Travis, but we should get a clean run



> A `UnhandledPromiseRejectionWarning` here: https://travis-ci.org/ampproject/amp-github-apps/builds/649548856#L253-L254
> 
> I'm ok with skipping tests since we just want to hook them up to Travis, but we should get a clean run

Resolved when I rebased :)

**Comment by estherkim** [comment]
Looks like `INVITE` is missing from `build-targets.js`

**Pull request merged**
