### PR TITLE
Delete checklist/ 

### PR DESCRIPTION
**Pull request by estherkim**
Because it's not being used or worked on.

### CODE REVIEW

**Comment by danielrozenberg** [comment]
@alanorozco intended on creating this but never got around to it. ok to delete? (of course this can always be recovered later)

**Comment by alanorozco** [comment]
Totally fine to delete. Thanks!

- A Github Workflow or a collection thereof would be more appropriate than a bot at this point.
- We're likely reworking PR templates in a way that would make this less useful.

**Comment by estherkim** [comment]
Both sound great. If we can get access to GitHub forms for issues, that might help a lot too!

That said, can I get a ✅ ✅ ✅

**Review by alanorozco — APPROVED** [review]

**Review by danielrozenberg — APPROVED** [review]
Proxying approval

**Pull request merged**
